<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <UseAppHost>false</UseAppHost>
        <Version>1.2.0</Version>
        <LangVersion>14</LangVersion>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Acme.OOProgramming.Tests" />
    </ItemGroup>
</Project>
